### ISSUE TITLE
Buggy filter functionality

### ISSUE THREAD

**Issue by lisbethpurrucker** [quouch/quouch#67]
I caught two bugs:

1. A `500` is returned once I am filtering for more than two categories. If I filter for characteristics & offer, the http request is successful and the right couches are returned. Once I add a city/country, it fails. Happens in any combination of three filters.
2. The clear filter link only works on the first page.

Debugging done so far:
1. Error thrown in console:

> ActiveRecord::StatementInvalid (PG::GroupingError: ERROR:  column "pg_search_f35fa88ea3370a67b353fc.rank" must appear in the GROUP BY clause or be used in an aggregate function
> LINE 1: ...(COUNT(DISTINCT characteristics.id) = 1) ORDER BY pg_search_...
>                                                              ^
> ):
>   
> app/controllers/concerns/couches_concern.rb:25:in `index'

2. Doubled checked in the `characteristics_filter_controller.js` and the form reset creates a clean url with no params, but the DOM is not updated appropriately. The url doesn't update either, so I added a `history.pushState(null, '', url);` which clears the url, but the params seem to persist from the last filtering as the checkboxes appear to still be checked and the input field still filled.

**Comment by lisbethpurrucker** [comment]
@papotte I am stuck here, pls help.

**Comment by papotte** [comment]
I'm splitting the second issue into its own ticket!
